import type {AppLocale} from '../../../shared/i18n/appLocale';

const pt = {
  title: 'Grupos', subtitle: 'Crie uma maré de constância com quem você gosta.',
  empty: 'NENHUM GRUPO ATIVO', emptyTitle: 'Sua equipe começa aqui',
  emptyDescription: 'Convide até quatro amigos e acompanhem juntos um desafio privado de sete dias.',
  openSlots: (name: string) => `${name} e quatro vagas disponíveis`,
  slot: 'Vaga', create: 'Criar grupo', join: 'Entrar com código',
  how: 'Como funciona', people: 'pessoas', days: 'dias', points: 'pontos',
  step1: 'Forme sua equipe', step1Description: 'Crie um grupo ou aceite um convite privado.',
  step2: 'Bebam no próprio ritmo', step2Description: 'Cada pessoa mantém sua meta diária individual.',
  step3: 'Subam no placar', step3Description: 'Cada dia vale até 100 pontos durante o desafio.',
  privacy: 'Privado por padrão', privacyDescription: 'Somente integrantes aceitos podem ver o progresso e o placar do grupo.',
  loading: 'Buscando sua equipe…', retry: 'Tentar novamente', refresh: 'Atualizar equipe',
  loadError: 'Não foi possível carregar sua equipe. Tente novamente.',
  networkError: 'Sem conexão com o servidor. Conecte-se à internet e tente novamente.',
  actionError: 'Não foi possível concluir. Tente novamente.',
  invalidInvite: 'O convite é inválido ou expirou. Peça um novo código ao responsável.',
  full: 'Este grupo já tem cinco integrantes.', alreadyJoined: 'Você já participa de um grupo. Atualizamos sua equipe.',
  ownerRequired: 'Somente o líder pode realizar esta ação.', rateLimit: 'Muitas tentativas. Aguarde um minuto e tente novamente.',
  validationError: 'Confira os dados informados e tente novamente.',
  groupName: 'Nome do grupo', namePlaceholder: 'Ex.: Maré de amigos', nameHint: 'Escolha um nome de 3 a 60 caracteres.',
  createDescription: 'Você será o responsável. Depois, compartilhe o código com até quatro amigos.',
  code: 'Código de convite', codePlaceholder: '12 letras ou números', codeHint: 'Digite o código de 12 caracteres que você recebeu.',
  joinDescription: 'Confira a equipe antes de aceitar o convite.', preview: 'Conferir convite',
  accept: 'Aceitar e entrar', consent: 'Ao entrar, seu nome e avatar ficam visíveis para os integrantes. Durante um desafio, seu progresso também será compartilhado.',
  cancel: 'Cancelar', back: 'Usar outro código', working: 'Aguarde…',
  active: 'SUA EQUIPE', members: 'Integrantes', member: 'Integrante', owner: 'Responsável', you: 'Você',
  memberCount: (count: number, max: number) => `${count} de ${max} integrantes`,
  waiting: 'Convide alguém para começar a formar sua equipe.', together: 'Sua equipe já está reunida. Cada gole conta para criar o hábito.',
  timezone: 'Fuso do grupo', invite: 'Convite privado', share: 'Compartilhar convite', renew: 'Gerar novo código',
  inviteHint: 'O código permite entrar na sua equipe. Compartilhe apenas com quem você quer convidar.',
  expires: (date: string) => `Válido até ${date}`, expired: 'Este convite expirou. Gere um novo código.',
  askOwner: 'Peça ao responsável para convidar mais pessoas.',
  shareMessage: (name: string, code: string) => `Venha para o grupo “${name}” no Aqualino! Na aba Grupos, toque em “Entrar com código” e use: ${code}`,
  renewTitle: 'Substituir o convite?', renewDescription: 'O código atual deixará de funcionar. Os integrantes continuam na equipe.',
  leave: 'Sair do grupo', leaveTitle: 'Sair desta equipe?',
  leaveDescription: 'Você deixará de ter acesso à equipe. Para voltar, será preciso aceitar um convite válido.',
  ownerLeaveDescription: 'A responsabilidade passa para o integrante mais antigo. Se você estiver sozinho, o grupo será encerrado.',
};

export type GroupsCopy = typeof pt;

export const groupsCopy: Record<AppLocale, GroupsCopy> = {
  'es-ES': {
    title: 'Grupos', subtitle: 'Crea una ola de constancia con quienes quieres.',
    empty: 'NINGÚN GRUPO ACTIVO', emptyTitle: 'Tu equipo empieza aquí',
    emptyDescription: 'Invita hasta a cuatro amigos y compartan un desafío privado de siete días.',
    openSlots: name => `${name} y cuatro plazas disponibles`,
    slot: 'Plaza', create: 'Crear grupo', join: 'Unirse con código',
    how: 'Cómo funciona', people: 'personas', days: 'días', points: 'puntos',
    step1: 'Forma tu equipo', step1Description: 'Crea un grupo o acepta una invitación privada.',
    step2: 'Beban a su propio ritmo', step2Description: 'Cada persona mantiene su propia meta diaria.',
    step3: 'Suban en la clasificación', step3Description: 'Cada día vale hasta 100 puntos durante el desafío.',
    privacy: 'Privado por defecto', privacyDescription: 'Solo los miembros aceptados pueden ver el progreso y la clasificación del grupo.',
    loading: 'Buscando tu equipo…', retry: 'Intentar de nuevo', refresh: 'Actualizar equipo',
    loadError: 'No se pudo cargar tu equipo. Inténtalo de nuevo.',
    networkError: 'Sin conexión con el servidor. Conéctate a internet e inténtalo de nuevo.',
    actionError: 'No se pudo completar la acción. Inténtalo de nuevo.',
    invalidInvite: 'La invitación no es válida o ha caducado. Pide un código nuevo al responsable.',
    full: 'Este grupo ya tiene cinco miembros.', alreadyJoined: 'Ya perteneces a un grupo. Hemos actualizado tu equipo.',
    ownerRequired: 'Solo el líder puede realizar esta acción.', rateLimit: 'Demasiados intentos. Espera un minuto e inténtalo de nuevo.',
    validationError: 'Comprueba los datos e inténtalo de nuevo.',
    groupName: 'Nombre del grupo', namePlaceholder: 'Ej.: Marea de amigos', nameHint: 'Elige un nombre de entre 3 y 60 caracteres.',
    createDescription: 'Serás el responsable. Después, comparte el código con hasta cuatro amigos.',
    code: 'Código de invitación', codePlaceholder: '12 letras o números', codeHint: 'Introduce el código de 12 caracteres que recibiste.',
    joinDescription: 'Revisa el equipo antes de aceptar la invitación.', preview: 'Revisar invitación',
    accept: 'Aceptar y unirse', consent: 'Al unirte, los miembros podrán ver tu nombre y avatar. Durante un desafío, también se compartirá tu progreso.',
    cancel: 'Cancelar', back: 'Usar otro código', working: 'Espera…',
    active: 'TU EQUIPO', members: 'Miembros', member: 'Miembro', owner: 'Responsable', you: 'Tú',
    memberCount: (count, max) => `${count} de ${max} miembros`,
    waiting: 'Invita a alguien para empezar a formar tu equipo.', together: 'Tu equipo ya está reunido. Cada sorbo cuenta para crear el hábito.',
    timezone: 'Zona horaria del grupo', invite: 'Invitación privada', share: 'Compartir invitación', renew: 'Generar un código nuevo',
    inviteHint: 'El código permite unirse a tu equipo. Compártelo solo con quienes quieras invitar.',
    expires: date => `Válido hasta ${date}`, expired: 'Esta invitación ha caducado. Genera un código nuevo.',
    askOwner: 'Pide al responsable que invite a más personas.',
    shareMessage: (name, code) => `¡Únete al grupo «${name}» en Aqualino! En la pestaña Grupos, toca «Unirse con código» e introduce: ${code}`,
    renewTitle: '¿Reemplazar la invitación?', renewDescription: 'El código actual dejará de funcionar. Los miembros seguirán en el equipo.',
    leave: 'Salir del grupo', leaveTitle: '¿Salir de este equipo?',
    leaveDescription: 'Perderás el acceso al equipo. Para volver, tendrás que aceptar una invitación válida.',
    ownerLeaveDescription: 'El miembro más antiguo pasará a ser el responsable. Si estás solo, el grupo se cerrará.',
  },
  'pt-BR': pt,
  'en-US': {
    title: 'Groups', subtitle: 'Build a wave of consistency with people you like.',
    empty: 'NO ACTIVE GROUP', emptyTitle: 'Your team starts here',
    emptyDescription: 'Invite up to four friends and follow a private seven-day challenge together.',
    openSlots: name => `${name} and four available spots`,
    slot: 'Spot', create: 'Create group', join: 'Join with code',
    how: 'How it works', people: 'people', days: 'days', points: 'points',
    step1: 'Build your team', step1Description: 'Create a group or accept a private invitation.',
    step2: 'Drink at your own pace', step2Description: 'Everyone keeps their own daily goal.',
    step3: 'Climb the leaderboard', step3Description: 'Each day is worth up to 100 points during a challenge.',
    privacy: 'Private by default', privacyDescription: 'Only accepted members can see the group’s progress and leaderboard.',
    loading: 'Finding your team…', retry: 'Try again', refresh: 'Refresh team',
    loadError: 'We could not load your team. Try again.',
    networkError: 'Cannot connect to the server. Connect to the internet and try again.',
    actionError: 'We could not complete this action. Try again.',
    invalidInvite: 'This invitation is invalid or expired. Ask the owner for a new code.',
    full: 'This group already has five members.', alreadyJoined: 'You already belong to a group. We refreshed your team.',
    ownerRequired: 'Only the leader can perform this action.', rateLimit: 'Too many attempts. Wait a minute and try again.',
    validationError: 'Check your details and try again.',
    groupName: 'Group name', namePlaceholder: 'E.g. Wave of friends', nameHint: 'Choose a name with 3 to 60 characters.',
    createDescription: 'You will be the owner. Then share the code with up to four friends.',
    code: 'Invitation code', codePlaceholder: '12 letters or numbers', codeHint: 'Enter the 12-character code you received.',
    joinDescription: 'Check the team before accepting the invitation.', preview: 'Check invitation',
    accept: 'Accept and join', consent: 'By joining, your name and avatar become visible to members. During a challenge, your progress will also be shared.',
    cancel: 'Cancel', back: 'Use another code', working: 'Please wait…',
    active: 'YOUR TEAM', members: 'Members', member: 'Member', owner: 'Owner', you: 'You',
    memberCount: (count, max) => `${count} of ${max} members`,
    waiting: 'Invite someone to start building your team.', together: 'Your team is together. Every sip helps build the habit.',
    timezone: 'Group time zone', invite: 'Private invitation', share: 'Share invitation', renew: 'Generate new code',
    inviteHint: 'This code lets people join your team. Only share it with people you want to invite.',
    expires: date => `Valid until ${date}`, expired: 'This invitation has expired. Generate a new code.',
    askOwner: 'Ask the owner to invite more people.',
    shareMessage: (name, code) => `Join “${name}” on Aqualino! In the Groups tab, tap “Join with code” and enter: ${code}`,
    renewTitle: 'Replace invitation?', renewDescription: 'The current code will stop working. Members will stay in the team.',
    leave: 'Leave group', leaveTitle: 'Leave this team?',
    leaveDescription: 'You will lose access to this team. To return, you will need to accept a valid invitation.',
    ownerLeaveDescription: 'The earliest member will become the owner. If you are alone, the group will close.',
  },
};
