import type {AchievementCode} from '@aqualino/contracts';
import type {AppLocale} from '../../../shared/i18n/appLocale';

const pt = {
  title: 'Conquistas', subtitle: 'Pequenos passos. Grandes marés.', highlights: 'Seus destaques',
  all: 'Ver todas as conquistas', profileHint: 'Abre sua coleção completa de conquistas',
  earned: 'Conquistadas', earnedBadge: 'Conquistada', allFilter: 'Todas', lockedFilter: 'A conquistar', locked: 'Ainda por conquistar',
  beginnings: 'Primeiros passos', consistency: 'Constância', goals: 'Suas metas', levels: 'Níveis permanentes',
  newAchievement: 'NOVA CONQUISTA', congratulations: 'Você fez acontecer!',
  saved: 'Mais um marco na sua jornada.', continue: 'Continuar', close: 'Fechar',
  back: 'Voltar ao perfil', swipeHint: 'Deslize para a direita para voltar',
  loading: 'Carregando sua coleção…', error: 'Não foi possível atualizar as conquistas.', retry: 'Tentar novamente',
  offline: 'Exibindo a coleção salva neste aparelho.', empty: 'Sua primeira conquista está a um pequeno passo.',
  noLocked: 'Você conquistou toda esta coleção!', progress: 'Progresso',
  collectionCount: (earned: number, total: number) => `${earned} de ${total} conquistas`,
  unlockedOn: (date: string) => `Conquistada em ${date}`,
  progressLabel: (progress: number, target: number) => `${progress} de ${target}`,
  items: {
    level_5: {title: 'Nível 5', description: 'Acumule XP até alcançar o nível 5.', celebration: 'Seu cuidado ganhou uma medalha verde. Este nível é seu para sempre!'},
    level_10: {title: 'Nível 10', description: 'Acumule XP até alcançar o nível 10.', celebration: 'Uma medalha azul para celebrar o nível 10. Continue no seu ritmo!'},
    level_50: {title: 'Nível 50', description: 'Acumule XP até alcançar o nível 50.', celebration: 'Sua medalha roxa marca uma longa jornada de cuidado!'},
    level_100: {title: 'Nível 100', description: 'Acumule XP até alcançar o nível 100.', celebration: 'Sua medalha dourada chegou! A jornada continua além do nível 100.'},
    first_drop: {title: 'Primeira gota', description: 'Faça seu primeiro registro de água.', celebration: 'O primeiro gole de uma nova jornada. Seu Aqualino está com você!'},
    first_reminder: {title: 'Na hora certa', description: 'Crie seu primeiro lembrete de hidratação.', celebration: 'Um carinho para o seu eu do futuro. Seu primeiro lembrete está pronto!'},
    first_goal: {title: 'Dia completo', description: 'Alcance sua meta diária pela primeira vez.', celebration: 'Você chegou à sua meta. Celebre o cuidado de hoje, no seu ritmo!'},
    team_player: {title: 'Em equipe', description: 'Crie ou entre no seu primeiro grupo.', celebration: 'Cuidar de si também pode ser uma jornada compartilhada!'},
    streak_3: {title: 'Em ritmo', description: 'Alcance uma sequência de 3 dias de hidratação.', celebration: 'Três dias de constância. Seu hábito está ganhando ritmo!'},
    streak_7: {title: 'Semana azul', description: 'Alcance uma sequência de 7 dias de hidratação.', celebration: 'Uma semana de cuidado, uma gota de cada vez!'},
    streak_14: {title: 'Maré constante', description: 'Alcance uma sequência de 14 dias de hidratação.', celebration: 'Duas semanas de constância. Seu cuidado já deixa marcas bonitas!'},
    streak_30: {title: 'Guardião das gotas', description: 'Alcance uma sequência de 30 dias de hidratação.', celebration: 'Trinta dias de jornada. Um hábito construído por você!'},
    goals_7: {title: 'Sete dias de cuidado', description: 'Alcance sua meta em 7 dias, seguidos ou não.', celebration: 'Sete metas atingidas. Cada dia de cuidado merece ser celebrado!'},
    goals_30: {title: 'Oceano de cuidado', description: 'Alcance sua meta em 30 dias, seguidos ou não.', celebration: 'Trinta metas atingidas. Seu oceano é feito de pequenos cuidados!'},
  } satisfies Record<AchievementCode, {title: string; description: string; celebration: string}>,
};
export type AchievementCopy = typeof pt;
export const achievementCopy: Record<AppLocale, AchievementCopy> = {
  'es-ES': {
    title: 'Logros', subtitle: 'Pequeños pasos. Grandes mareas.', highlights: 'Tus destacados',
    all: 'Ver todos los logros', profileHint: 'Abre tu colección completa de logros',
    earned: 'Conseguidos', earnedBadge: 'Conseguido', allFilter: 'Todos', lockedFilter: 'Por conseguir', locked: 'Aún por conseguir',
    beginnings: 'Primeros pasos', consistency: 'Constancia', goals: 'Tus metas', levels: 'Niveles permanentes',
    newAchievement: 'NUEVO LOGRO', congratulations: '¡Lo has conseguido!',
    saved: 'Otro hito en tu camino.', continue: 'Continuar', close: 'Cerrar',
    back: 'Volver al perfil', swipeHint: 'Desliza hacia la derecha para volver',
    loading: 'Cargando tu colección…', error: 'No se pudieron actualizar los logros.', retry: 'Intentar de nuevo',
    offline: 'Mostrando la colección guardada en este dispositivo.', empty: 'Tu primer logro está a un pequeño paso.',
    noLocked: '¡Has conseguido toda esta colección!', progress: 'Progreso',
    collectionCount: (earned, total) => `${earned} de ${total} logros`,
    unlockedOn: date => `Conseguido el ${date}`, progressLabel: (progress, target) => `${progress} de ${target}`,
    items: {
      level_5: {title: 'Nivel 5', description: 'Acumula XP hasta alcanzar el nivel 5.', celebration: 'Una medalla verde por cuidarte. ¡Este nivel es tuyo para siempre!'},
      level_10: {title: 'Nivel 10', description: 'Acumula XP hasta alcanzar el nivel 10.', celebration: 'Una medalla azul para celebrar el nivel 10. ¡Sigue a tu ritmo!'},
      level_50: {title: 'Nivel 50', description: 'Acumula XP hasta alcanzar el nivel 50.', celebration: '¡Tu medalla morada marca un largo camino de cuidado!'},
      level_100: {title: 'Nivel 100', description: 'Acumula XP hasta alcanzar el nivel 100.', celebration: '¡Llegó tu medalla dorada! El camino continúa más allá del nivel 100.'},
      first_drop: {title: 'Primera gota', description: 'Registra agua por primera vez.', celebration: 'El primer sorbo de un nuevo camino. ¡Aqualino está contigo!'},
      first_reminder: {title: 'A tiempo', description: 'Crea tu primer recordatorio de hidratación.', celebration: 'Un gesto de cuidado para tu yo del futuro. ¡Tu primer recordatorio está listo!'},
      first_goal: {title: 'Día completo', description: 'Alcanza tu meta diaria por primera vez.', celebration: 'Has alcanzado tu meta. ¡Celebra el cuidado de hoy, a tu ritmo!'},
      team_player: {title: 'En equipo', description: 'Crea o únete a tu primer grupo.', celebration: '¡Cuidarte también puede ser un camino compartido!'},
      streak_3: {title: 'A buen ritmo', description: 'Alcanza una racha de 3 días de hidratación.', celebration: 'Tres días de constancia. ¡Tu hábito está tomando ritmo!'},
      streak_7: {title: 'Semana azul', description: 'Alcanza una racha de 7 días de hidratación.', celebration: '¡Una semana de cuidado, una gota a la vez!'},
      streak_14: {title: 'Marea constante', description: 'Alcanza una racha de 14 días de hidratación.', celebration: 'Dos semanas de constancia. ¡Tu cuidado ya deja huella!'},
      streak_30: {title: 'Guardián de las gotas', description: 'Alcanza una racha de 30 días de hidratación.', celebration: 'Treinta días de camino. ¡Un hábito construido por ti!'},
      goals_7: {title: 'Siete días de cuidado', description: 'Alcanza tu meta en 7 días, consecutivos o no.', celebration: 'Siete metas alcanzadas. ¡Cada día de cuidado merece celebrarse!'},
      goals_30: {title: 'Océano de cuidado', description: 'Alcanza tu meta en 30 días, consecutivos o no.', celebration: 'Treinta metas alcanzadas. ¡Tu océano está hecho de pequeños cuidados!'},
    },
  },
  'pt-BR': pt,
  'en-US': {
    title: 'Achievements', subtitle: 'Small steps. Great waves.', highlights: 'Your highlights',
    all: 'View all achievements', profileHint: 'Opens your complete achievement collection',
    earned: 'Earned', earnedBadge: 'Earned', allFilter: 'All', lockedFilter: 'To earn', locked: 'Still to earn',
    beginnings: 'First steps', consistency: 'Consistency', goals: 'Your goals', levels: 'Permanent levels',
    newAchievement: 'NEW ACHIEVEMENT', congratulations: 'You made it happen!',
    saved: 'Another milestone on your journey.', continue: 'Continue', close: 'Close',
    back: 'Back to profile', swipeHint: 'Swipe right to go back',
    loading: 'Loading your collection…', error: 'We could not refresh your achievements.', retry: 'Try again',
    offline: 'Showing the collection saved on this device.', empty: 'Your first achievement is one small step away.',
    noLocked: 'You have earned this entire collection!', progress: 'Progress',
    collectionCount: (earned, total) => `${earned} of ${total} achievements`,
    unlockedOn: date => `Earned on ${date}`, progressLabel: (progress, target) => `${progress} of ${target}`,
    items: {
      level_5: {title: 'Level 5', description: 'Collect XP to reach level 5.', celebration: 'A green medal for your care. This level is yours to keep!'},
      level_10: {title: 'Level 10', description: 'Collect XP to reach level 10.', celebration: 'A blue medal to celebrate level 10. Keep going at your own pace!'},
      level_50: {title: 'Level 50', description: 'Collect XP to reach level 50.', celebration: 'Your purple medal marks a long journey of care!'},
      level_100: {title: 'Level 100', description: 'Collect XP to reach level 100.', celebration: 'Your gold medal is here! Your journey continues beyond level 100.'},
      first_drop: {title: 'First drop', description: 'Record water for the first time.', celebration: 'The first sip of a new journey. Aqualino is here with you!'},
      first_reminder: {title: 'Right on time', description: 'Create your first hydration reminder.', celebration: 'A little care for your future self. Your first reminder is ready!'},
      first_goal: {title: 'A complete day', description: 'Reach your daily goal for the first time.', celebration: 'You reached your goal. Celebrate today’s care, at your own pace!'},
      team_player: {title: 'Better together', description: 'Create or join your first group.', celebration: 'Taking care of yourself can be a shared journey too!'},
      streak_3: {title: 'Finding your rhythm', description: 'Reach a 3-day hydration streak.', celebration: 'Three days of consistency. Your habit is finding its rhythm!'},
      streak_7: {title: 'Blue week', description: 'Reach a 7-day hydration streak.', celebration: 'A week of care, one drop at a time!'},
      streak_14: {title: 'Steady tide', description: 'Reach a 14-day hydration streak.', celebration: 'Two weeks of consistency. Your care is making a difference!'},
      streak_30: {title: 'Keeper of drops', description: 'Reach a 30-day hydration streak.', celebration: 'Thirty days on your journey. A habit built by you!'},
      goals_7: {title: 'Seven days of care', description: 'Reach your goal on 7 days, consecutive or not.', celebration: 'Seven goals reached. Every day of care deserves a celebration!'},
      goals_30: {title: 'Ocean of care', description: 'Reach your goal on 30 days, consecutive or not.', celebration: 'Thirty goals reached. Your ocean is made of small acts of care!'},
    },
  },
};
