export const accountSecurityCopy = {
  'es-ES': {
    eyebrow: 'TU CUENTA AQUALINO', forgotLink: 'Olvidé mi contraseña',
    forgotTitle: 'Vamos a recuperar tu cuenta', forgotSubtitle: 'Introduce tu correo para recibir un enlace y crear una contraseña nueva.',
    email: 'Correo electrónico', emailPlaceholder: 'tu@ejemplo.com', sendLink: 'Enviar enlace de recuperación',
    sentTitle: 'Revisa tu correo', sentSubtitle: 'Si existe una cuenta con este correo, recibirás un enlace para restablecer la contraseña.',
    sentHint: 'El enlace es válido durante 60 minutos. Revisa también la carpeta de spam.',
    resend: 'Reenviar correo', resendIn: (seconds: number) => `Reenviar en ${seconds}s`,
    changeEmail: 'Usar otro correo', back: 'Volver', backToLogin: 'Volver al inicio de sesión',
    emailInvalid: 'Introduce un correo válido.', networkError: 'No se pudo conectar. Comprueba tu conexión e inténtalo de nuevo.',
    genericError: 'No se pudo completar la solicitud. Inténtalo de nuevo.', rateLimit: 'Espera un poco antes de intentarlo de nuevo.',
    verifyTitle: 'Confirma tu correo', verifySubtitle: 'Solo falta un paso para empezar tu camino con Aqualino.',
    verifyHint: 'Abre el correo de confirmación y toca el botón para activar tu cuenta. El enlace es válido durante 60 minutos.',
    verifyCheck: 'Ya confirmé mi correo', verifyPending: 'La confirmación aún no ha llegado. Abre el enlace enviado a tu correo e inténtalo de nuevo.',
    verifyResent: 'Correo solicitado. Revisa tu bandeja de entrada y la carpeta de spam.',
    useAnotherAccount: 'Cerrar sesión y usar otra cuenta', deliveryError: 'No se pudo enviar el correo. Inténtalo de nuevo en unos momentos.',
    sessionExpired: 'Tu sesión ha caducado. Inicia sesión de nuevo para continuar.',
    resetTitle: 'Crea una contraseña nueva', resetSubtitle: 'Elige una contraseña para retomar tu camino.',
    password: 'Contraseña nueva', confirmPassword: 'Confirmar contraseña nueva', passwordHint: 'Usa al menos 8 caracteres, con letras y números.',
    passwordInvalid: 'La contraseña debe tener entre 8 y 128 caracteres, con letras y números.', mismatch: 'Las contraseñas deben coincidir.',
    resetButton: 'Guardar contraseña nueva', invalidTitle: 'Vamos a pedir un enlace nuevo', invalidLink: 'Este enlace no es válido, ya se ha usado o ha caducado. Solicita otro para recuperar tu cuenta.',
    newLink: 'Solicitar un enlace nuevo', successTitle: '¡Contraseña actualizada!', successSubtitle: 'Tu cuenta está lista para continuar.',
    successHint: 'Inicia sesión con tu contraseña nueva. Por seguridad, se han cerrado las sesiones anteriores.', signIn: 'Entrar con la contraseña nueva',
    loginTitle: 'Qué bueno tenerte de vuelta', loginSubtitle: 'Inicia sesión para seguir cuidando tu hidratación.',
  },
  'pt-BR': {
    eyebrow: 'SUA CONTA AQUALINO', forgotLink: 'Esqueci minha senha',
    forgotTitle: 'Vamos recuperar sua conta', forgotSubtitle: 'Informe seu e-mail para receber um link e criar uma nova senha.',
    email: 'E-mail', emailPlaceholder: 'voce@exemplo.com', sendLink: 'Enviar link de recuperação',
    sentTitle: 'Confira seu e-mail', sentSubtitle: 'Se houver uma conta com esse e-mail, você receberá um link para redefinir a senha.',
    sentHint: 'O link vale por 60 minutos. Confira também a pasta de spam.',
    resend: 'Reenviar e-mail', resendIn: (seconds: number) => `Reenviar em ${seconds}s`,
    changeEmail: 'Usar outro e-mail', back: 'Voltar', backToLogin: 'Voltar para entrar',
    emailInvalid: 'Informe um e-mail válido.', networkError: 'Não foi possível conectar. Confira sua conexão e tente novamente.',
    genericError: 'Não foi possível concluir. Tente novamente.', rateLimit: 'Aguarde um pouco antes de tentar novamente.',
    verifyTitle: 'Confirme seu e-mail', verifySubtitle: 'Falta só um passo para começar sua jornada com o Aqualino.',
    verifyHint: 'Abra o e-mail de confirmação e toque no botão para ativar sua conta. O link vale por 60 minutos.',
    verifyCheck: 'Já confirmei meu e-mail', verifyPending: 'A confirmação ainda não chegou. Abra o link enviado ao seu e-mail e tente novamente.',
    verifyResent: 'E-mail solicitado. Confira sua caixa de entrada e a pasta de spam.',
    useAnotherAccount: 'Sair e usar outra conta', deliveryError: 'Não foi possível enviar o e-mail. Tente novamente em instantes.',
    sessionExpired: 'Sua sessão expirou. Entre novamente para continuar.',
    resetTitle: 'Crie uma nova senha', resetSubtitle: 'Escolha uma senha para voltar à sua jornada.',
    password: 'Nova senha', confirmPassword: 'Confirmar nova senha', passwordHint: 'Use pelo menos 8 caracteres, com letras e números.',
    passwordInvalid: 'A senha deve ter de 8 a 128 caracteres, com letras e números.', mismatch: 'As senhas precisam ser iguais.',
    resetButton: 'Salvar nova senha', invalidTitle: 'Vamos pedir um novo link', invalidLink: 'Este link é inválido, já foi usado ou expirou. Solicite outro para recuperar sua conta.',
    newLink: 'Solicitar novo link', successTitle: 'Senha atualizada!', successSubtitle: 'Sua conta está pronta para continuar.',
    successHint: 'Entre com sua nova senha. Por segurança, as sessões anteriores foram encerradas.', signIn: 'Entrar com a nova senha',
    loginTitle: 'Bom ter você de volta', loginSubtitle: 'Entre para continuar cuidando da sua hidratação.',
  },
  'en-US': {
    eyebrow: 'YOUR AQUALINO ACCOUNT', forgotLink: 'Forgot my password',
    forgotTitle: 'Let’s recover your account', forgotSubtitle: 'Enter your email to receive a link and create a new password.',
    email: 'Email', emailPlaceholder: 'you@example.com', sendLink: 'Send recovery link',
    sentTitle: 'Check your email', sentSubtitle: 'If an account uses this email, you will receive a link to reset your password.',
    sentHint: 'The link is valid for 60 minutes. Check your spam folder too.',
    resend: 'Resend email', resendIn: (seconds: number) => `Resend in ${seconds}s`,
    changeEmail: 'Use another email', back: 'Back', backToLogin: 'Back to sign in',
    emailInvalid: 'Enter a valid email.', networkError: 'Could not connect. Check your connection and try again.',
    genericError: 'Could not complete this request. Try again.', rateLimit: 'Please wait a little before trying again.',
    verifyTitle: 'Confirm your email', verifySubtitle: 'Just one more step to begin your Aqualino journey.',
    verifyHint: 'Open the confirmation email and tap the button to activate your account. The link is valid for 60 minutes.',
    verifyCheck: 'I have confirmed my email', verifyPending: 'Your email is still awaiting confirmation. Open the link in your email and try again.',
    verifyResent: 'Email requested. Check your inbox and spam folder.',
    useAnotherAccount: 'Sign out and use another account', deliveryError: 'Could not send the email. Please try again shortly.',
    sessionExpired: 'Your session has expired. Sign in again to continue.',
    resetTitle: 'Create a new password', resetSubtitle: 'Choose a password to return to your journey.',
    password: 'New password', confirmPassword: 'Confirm new password', passwordHint: 'Use at least 8 characters, including letters and numbers.',
    passwordInvalid: 'Use 8 to 128 characters, including letters and numbers.', mismatch: 'The passwords must match.',
    resetButton: 'Save new password', invalidTitle: 'Let’s get a new link', invalidLink: 'This link is invalid, has already been used, or has expired. Request another to recover your account.',
    newLink: 'Request a new link', successTitle: 'Password updated!', successSubtitle: 'Your account is ready to continue.',
    successHint: 'Sign in with your new password. For security, previous sessions have been signed out.', signIn: 'Sign in with new password',
    loginTitle: 'Good to see you again', loginSubtitle: 'Sign in to continue taking care of your hydration.',
  },
};

export type AccountSecurityCopy = typeof accountSecurityCopy['pt-BR'];
